/**
 * Style / shape tags for each index in POTTERY_FACTS (same order).
 * Tags overlap with `computePotShapeHint().tags` for similarity matching.
 */
export const FACT_STYLE_TAGS = [
  ['prehistoric', 'east_asia', 'early_vessel', 'balanced_vessel'],
  ['prehistoric', 'europe', 'figurine', 'sculptural'],
  ['japan', 'jomon', 'early', 'cord_marked', 'squat_wide'],
  ['neolithic', 'europe', 'banded', 'balanced_vessel'],
  ['ancient_tech', 'wheel', 'near_east', 'tall_vessel'],
  ['hand_build', 'coil', 'sculptural', 'large_form'],
  ['earthenware', 'low_fire', 'open_bowl'],
  ['stoneware', 'high_fire', 'stoneware_like', 'tall_vessel', 'storage_jar'],
  ['porcelain', 'fine', 'china', 'translucent'],
  ['china', 'porcelain', 'high_fire', 'kiln_tech'],
  ['china', 'blue_white', 'underglaze', 'belly_centered'],
  ['china', 'celadon', 'green_glaze', 'globular', 'song_era'],
  ['china', 'celadon', 'trade', 'stoneware_like', 'belly_centered'],
  ['china', 'carved', 'white_body', 'tall_necked'],
  ['china', 'tang', 'sancai', 'tomb', 'globular'],
  ['egypt', 'faience', 'ancient', 'glaze'],
  ['islamic', 'tin_glaze', 'middle_east', 'flared_opening'],
  ['islamic', 'ottoman', 'iznik', 'tile', 'bowl_form'],
  ['italy', 'maiolica', 'renaissance', 'tin_glaze', 'open_bowl'],
  ['europe', 'delft', 'dutch', 'tin_glaze', 'blue_white'],
  ['europe', 'porcelain', 'meissen', 'factory', 'belly_centered'],
  ['europe', 'industrial', 'wedgwood', 'neo_classical', 'stoneware_like'],
  ['britain', 'bone_china', 'porcelain', 'tea_ware'],
  ['stoneware', 'salt_glaze', 'europe', 'storage_jar'],
  ['japan', 'raku', 'tea_ware', 'tea', 'bowl_form', 'squat_wide'],
  ['greek', 'black_figure', 'classical_mediterranean', 'amphora_like', 'tall_necked'],
  ['greek', 'red_figure', 'classical_mediterranean', 'tall_vessel'],
  ['roman', 'terra_sigillata', 'tableware', 'open_bowl'],
  ['greek', 'amphora', 'tall_necked', 'storage_jar', 'classical_mediterranean'],
  ['andes', 'moche', 'portrait', 'stirrup', 'sculptural'],
  ['firing_tech', 'reduction', 'kiln', 'glaze_chemistry'],
  ['firing_tech', 'oxidation', 'earthenware'],
  ['process', 'bisque', 'studio'],
  ['decoration', 'sgraffito', 'slip', 'europe'],
  ['korea', 'buncheong', 'slip', 'stoneware_like', 'globular'],
  ['china', 'yixing', 'tea_ware', 'unglazed', 'squat_wide'],
  ['japan', 'kintsugi', 'repair', 'tea', 'bowl_form'],
  ['europe', 'slipware', 'staffordshire', 'trailing', 'open_bowl'],
  ['europe', 'industrial', 'transfer_print', 'tableware'],
  ['glaze_chemistry', 'lead', 'history'],
  ['egypt', 'pigment', 'blue', 'ancient'],
  ['kiln_tech', 'pyrometric', 'studio'],
  ['kiln_tech', 'saggar', 'protection'],
  ['japan', 'anagama', 'wood_fire', 'ash_glaze', 'stoneware_like'],
  ['decoration', 'underglaze', 'islamic', 'china'],
  ['china', 'overglaze', 'famille', 'enamel'],
  ['glaze_chemistry', 'crazing', 'technical'],
  ['archaeology', 'wasters', 'kiln'],
  ['china', 'neolithic', 'yangshao', 'painted', 'belly_centered'],
  ['china', 'industry', 'kiln_sites'],
  ['islamic', 'luster', 'metallic', 'third_fire'],
  ['europe', 'industrial', 'maiolica', 'tin_glaze'],
  ['process', 'wedging', 'studio'],
  ['process', 'slip', 'decoration'],
  ['process', 'engobe', 'slip'],
  ['pit_fire', 'primitive', 'low_fire', 'open_bowl'],
  ['native_americas', 'pueblo', 'polished', 'squat_wide'],
  ['modern', 'industrial', 'iso', 'tile'],
  ['china', 'jingdezhen', 'porcelain', 'petuntse'],
  ['china', 'cobalt', 'blue_white', 'trade'],
  ['europe', 'porcelain', 'soft_paste', 'imitation'],
  ['kiln_tech', 'downdraft', 'efficiency'],
  ['wood_fire', 'ash_glaze', 'stoneware', 'shoulder_pot'],
  ['glaze_chemistry', 'chrome', 'england', 'color'],
  ['glaze_chemistry', 'barium', 'technical'],
  ['glaze_chemistry', 'alumina', 'technical'],
  ['glaze_chemistry', 'zircon', 'industrial'],
  ['conservation', 'museum', 'archaeology'],
];
